export const interactionDatabase: Interaction[] = [
  {
    name: "Bupropion",
    type: "medication",
    severity: "Low",
    description: "May cause slight changes in blood sugar levels",
    recommendation: "Monitor blood sugar levels if using bupropion",
  },
  {
    name: "Metronidazole",
    type: "medication",
    severity: "Medium",
    description: "May increase the risk of low blood sugar when combined with Glipizide",
    recommendation: "Monitor blood sugar levels closely",
  },
  {
    name: "Fluoxetine",
    type: "medication",
    severity: "Low",
    description: "May cause slight changes in blood sugar levels",
    recommendation: "Monitor blood sugar levels if using fluoxetine",
  },
  {
    name: "Paroxetine",
    type: "medication",
    severity: "Low",
    description: "May cause slight changes in blood sugar levels",
    recommendation: "Monitor blood sugar levels if using paroxetine",
  },
  {
    name: "Sertraline",
    type: "medication",
    severity: "Low",
    description: "May cause slight changes in blood sugar levels",
    recommendation: "Monitor blood sugar levels if using sertraline",
  },
  {
    name: "Venlafaxine",
    type: "medication",
    severity: "Low",
    description: "May cause slight changes in blood sugar levels",
    recommendation: "Monitor blood sugar levels if using venlafaxine",
  },
  {
    name: "Duloxetine",
    type: "medication",
    severity: "Low",
    description: "May cause slight changes in blood sugar levels",
    recommendation: "Monitor blood sugar levels if using duloxetine",
  },
  {
    name: "Escitalopram",
    type: "medication",
    severity: "Low",
    description: "May cause slight changes in blood sugar levels",
    recommendation: "Monitor blood sugar levels if using escitalopram",
  },
  {
    name: "Citalopram",
    type: "medication",
    severity: "Low",
    description: "May cause slight changes in blood sugar levels",
    recommendation: "Monitor blood sugar levels if using citalopram",
  },
  {
    name: "Trazodone",
    type: "medication",
    severity: "Low",
    description: "May cause slight changes in blood sugar levels",
    recommendation: "Monitor blood sugar levels if using trazodone",
  },
  {
    name: "Mirtazapine",
    type: "medication",
    severity: "Low",
    description: "May cause slight changes in blood sugar levels",
    recommendation: "Monitor blood sugar levels if using mirtazapine",
  },
  {
    name: "Quetiapine",
    type: "medication",
    severity: "Medium",
    description: "May increase blood sugar levels, counteracting the effects of diabetes medications",
    recommendation: "Monitor blood sugar levels closely",
  },
  {
    name: "Olanzapine",
    type: "medication",
    severity: "High",
    description: "May increase blood sugar levels, counteracting the effects of diabetes medications",
    recommendation: "Monitor blood sugar levels closely and consult your doctor",
  },
  {
    name: "Risperidone",
    type: "medication",
    severity: "Medium",
    description: "May increase blood sugar levels, counteracting the effects of diabetes medications",
    recommendation: "Monitor blood sugar levels closely",
  },
  {
    name: "Aripiprazole",
    type: "medication",
    severity: "Medium",
    description: "May increase blood sugar levels, counteracting the effects of diabetes medications",
    recommendation: "Monitor blood sugar levels closely",
  },
  {
    name: "Ziprasidone",
    type: "medication",
    severity: "Medium",
    description: "May increase blood sugar levels, counteracting the effects of diabetes medications",
    recommendation: "Monitor blood sugar levels closely",
  },
  {
    name: "Clozapine",
    type: "medication",
    severity: "High",
    description: "May increase blood sugar levels, counteracting the effects of diabetes medications",
    recommendation: "Monitor blood sugar levels closely and consult your doctor",
  },
  {
    name: "Lithium",
    type: "medication",
    severity: "Medium",
    description: "May affect blood sugar levels when combined with diabetes medications",
    recommendation: "Monitor blood sugar levels and lithium levels closely",
  },
  {
    name: "Valproic Acid",
    type: "medication",
    severity: "Medium",
    description: "May increase blood sugar levels, counteracting the effects of diabetes medications",
    recommendation: "Monitor blood sugar levels closely",
  },
  {
    name: "Carbamazepine",
    type: "medication",
    severity: "High",
    description: "May reduce the effectiveness of Glipizide",
    recommendation: "Avoid or consult your doctor before using this combination",
  },
  {
    name: "Phenytoin",
    type: "medication",
    severity: "High",
    description: "May reduce the effectiveness of Glipizide",
    recommendation: "Avoid or consult your doctor before using this combination",
  },
  {
    name: "Phenobarbital",
    type: "medication",
    severity: "High",
    description: "May reduce the effectiveness of Glipizide",
    recommendation: "Avoid or consult your doctor before using this combination",
  },
  {
    name: "Lamotrigine",
    type: "medication",
    severity: "Low",
    description: "May cause slight changes in blood sugar levels",
    recommendation: "Monitor blood sugar levels if using lamotrigine",
  },
  {
    name: "Topiramate",
    type: "medication",
    severity: "Medium",
    description: "May affect blood sugar control when combined with diabetes medications",
    recommendation: "Monitor blood sugar levels closely",
  },
  {
    name: "Gabapentin",
    type: "medication",
    severity: "Low",
    description: "May cause slight changes in blood sugar levels",
    recommendation: "Monitor blood sugar levels if using gabapentin",
  },
  {
    name: "Pregabalin",
    type: "medication",
    severity: "Low",
    description: "May cause slight changes in blood sugar levels",
    recommendation: "Monitor blood sugar levels if using pregabalin",
  },
  {
    name: "Levetiracetam",
    type: "medication",
    severity: "Low",
    description: "May cause slight changes in blood sugar levels",
    recommendation: "Monitor blood sugar levels if using levetiracetam",
  },
  {
    name: "Oxcarbazepine",
    type: "medication",
    severity: "Low",
    description: "May cause slight changes in blood sugar levels",
    recommendation: "Monitor blood sugar levels if using oxcarbazepine",
  },
  {
    name: "Tiagabine",
    type: "medication",
    severity: "Low",
    description: "May cause slight changes in blood sugar levels",
    recommendation: "Monitor blood sugar levels if using tiagabine",
  },
  {
    name: "Zonisamide",
    type: "medication",
    severity: "Low",
    description: "May cause slight changes in blood sugar levels",
    recommendation: "Monitor blood sugar levels if using zonisamide",
  },
  {
    name: "Vigabatrin",
    type: "medication",
    severity: "Low",
    description: "May cause slight changes in blood sugar levels",
    recommendation: "Monitor blood sugar levels if using vigabatrin",
  },
  {
    name: "Felbamate",
    type: "medication",
    severity: "Low",
    description: "May cause slight changes in blood sugar levels",
    recommendation: "Monitor blood sugar levels if using felbamate",
  },
  {
    name: "Primidone",
    type: "medication",
    severity: "Low",
    description: "May cause slight changes in blood sugar levels",
    recommendation: "Monitor blood sugar levels if using primidone",
  },
  {
    name: "Ethosuximide",
    type: "medication",
    severity: "Low",
    description: "May cause slight changes in blood sugar levels",
    recommendation: "Monitor blood sugar levels if using ethosuximide",
  },
  {
    name: "Clonazepam",
    type: "medication",
    severity: "Low",
    description: "May cause slight changes in blood sugar levels",
    recommendation: "Monitor blood sugar levels if using clonazepam",
  },
  {
    name: "Lorazepam",
    type: "medication",
    severity: "Low",
    description: "May cause slight changes in blood sugar levels",
    recommendation: "Monitor blood sugar levels if using lorazepam",
  },
  {
    name: "Diazepam",
    type: "medication",
    severity: "Low",
    description: "May cause slight changes in blood sugar levels",
    recommendation: "Monitor blood sugar levels if using diazepam",
  },
  {
    name: "Alprazolam",
    type: "medication",
    severity: "Low",
    description: "May cause slight changes in blood sugar levels",
    recommendation: "Monitor blood sugar levels if using alprazolam",
  },
  {
    name: "Temazepam",
    type: "medication",
    severity: "Low",
    description: "May cause slight changes in blood sugar levels",
    recommendation: "Monitor blood sugar levels if using temazepam",
  },
  {
    name: "Zolpidem",
    type: "medication",
    severity: "Low",
    description: "May cause slight changes in blood sugar levels",
    recommendation: "Monitor blood sugar levels if using zolpidem",
  },
  {
    name: "Eszopiclone",
    type: "medication",
    severity: "Low",
    description: "May cause slight changes in blood sugar levels",
    recommendation: "Monitor blood sugar levels if using eszopiclone",
  },
  {
    name: "Ramelteon",
    type: "medication",
    severity: "Low",
    description: "May cause slight changes in blood sugar levels",
    recommendation: "Monitor blood sugar levels if using ramelteon",
  },
  {
    name: "Suvorexant",
    type: "medication",
    severity: "Low",
    description: "May cause slight changes in blood sugar levels",
    recommendation: "Monitor blood sugar levels if using suvorexant",
  },
  {
    name: "Doxepin",
    type: "medication",
    severity: "Low",
    description: "May cause slight changes in blood sugar levels",
    recommendation: "Monitor blood sugar levels if using doxepin",
  },
  {
    name: "Amitriptyline",
    type: "medication",
    severity: "Low",
    description: "May cause slight changes in blood sugar levels",
    recommendation: "Monitor blood sugar levels if using amitriptyline",
  },
  {
    name: "Nortriptyline",
    type: "medication",
    severity: "Low",
    description: "May cause slight changes in blood sugar levels",
    recommendation: "Monitor blood sugar levels if using nortriptyline",
  },
  {
    name: "Imipramine",
    type: "medication",
    severity: "Low",
    description: "May cause slight changes in blood sugar levels",
    recommendation: "Monitor blood sugar levels if using imipramine",
  },
  {
    name: "Desipramine",
    type: "medication",
    severity: "Low",
    description: "May cause slight changes in blood sugar levels",
    recommendation: "Monitor blood sugar levels if using desipramine",
  },
  {
    name: "Clomipramine",
    type: "medication",
    severity: "Low",
    description: "May cause slight changes in blood sugar levels",
    recommendation: "Monitor blood sugar levels if using clomipramine",
  },
  {
    name: "Protriptyline",
    type: "medication",
    severity: "Low",
    description: "May cause slight changes in blood sugar levels",
    recommendation: "Monitor blood sugar levels if using protriptyline",
  },
  {
    name: "Trimipramine",
    type: "medication",
    severity: "Low",
    description: "May cause slight changes in blood sugar levels",
    recommendation: "Monitor blood sugar levels if using trimipramine",
  },
  {
    name: "Maprotiline",
    type: "medication",
    severity: "Low",
    description: "May cause slight changes in blood sugar levels",
    recommendation: "Monitor blood sugar levels if using maprotiline",
  },
  {
    name: "Amoxapine",
    type: "medication",
    severity: "Low",
    description: "May cause slight changes in blood sugar levels",
    recommendation: "Monitor blood sugar levels if using amoxapine",
  },
  {
    name: "Trazodone",
    type: "medication",
    severity: "Low",
    description: "May cause slight changes in blood sugar levels",
    recommendation: "Monitor blood sugar levels if using trazodone",
  },
  {
    name: "Nefazodone",
    type: "medication",
    severity: "Low",
    description: "May cause slight changes in blood sugar levels",
    recommendation: "Monitor blood sugar levels if using nefazodone",
  },
  {
    name: "Mirtazapine",
    type: "medication",
    severity: "Low",
    description: "May cause slight changes in blood sugar levels",
    recommendation: "Monitor blood sugar levels if using mirtazapine",
  },
  {
    name: "Bupropion",
    type: "medication",
    severity: "Low",
    description: "May cause slight changes in blood sugar levels",
    recommendation: "Monitor blood sugar levels if using bupropion",
  },
  {
    name: "Venlafaxine",
    type: "medication",
    severity: "Low",
    description: "May cause slight changes in blood sugar levels",
    recommendation: "Monitor blood sugar levels if using venlafaxine",
  },
  {
    name: "Duloxetine",
    type: "medication",
    severity: "Low",
    description: "May cause slight changes in blood sugar levels",
    recommendation: "Monitor blood sugar levels if using duloxetine",
  },
  {
    name: "Desvenlafaxine",
    type: "medication",
    severity: "Low",
    description: "May cause slight changes in blood sugar levels",
    recommendation: "Monitor blood sugar levels if using desvenlafaxine",
  },
  {
    name: "Levomilnacipran",
    type: "medication",
    severity: "Low",
    description: "May cause slight changes in blood sugar levels",
    recommendation: "Monitor blood sugar levels if using levomilnacipran",
  },
  {
    name: "Vilazodone",
    type: "medication",
    severity: "Low",
    description: "May cause slight changes in blood sugar levels",
    recommendation: "Monitor blood sugar levels if using vilazodone",
  },
  {
    name: "Vortioxetine",
    type: "medication",
    severity: "Low",
    description: "May cause slight changes in blood sugar levels",
    recommendation: "Monitor blood sugar levels if using vortioxetine",
  },
  {
    name: "Selegiline",
    type: "medication",
    severity: "Low",
    description: "May cause slight changes in blood sugar levels",
    recommendation: "Monitor blood sugar levels if using selegiline",
  },
  {
    name: "Rasagiline",
    type: "medication",
    severity: "Low",
    description: "May cause slight changes in blood sugar levels",
    recommendation: "Monitor blood sugar levels if using rasagiline",
  },
  {
    name: "Safinamide",
    type: "medication",
    severity: "Low",
    description: "May cause slight changes in blood sugar levels",
    recommendation: "Monitor blood sugar levels if using safinamide",
  },
  {
    name: "Phenelzine",
    type: "medication",
    severity: "Low",
    description: "May cause slight changes in blood sugar levels",
    recommendation: "Monitor blood sugar levels if using phenelzine",
  },
  {
    name: "Tranylcypromine",
    type: "medication",
    severity: "Low",
    description: "May cause slight changes in blood sugar levels",
    recommendation: "Monitor blood sugar levels if using tranylcypromine",
  },
  {
    name: "Isocarboxazid",
    type: "medication",
    severity: "Low",
    description: "May cause slight changes in blood sugar levels",
    recommendation: "Monitor blood sugar levels if using isocarboxazid",
  },
  {
    name: "Moclobemide",
    type: "medication",
    severity: "Low",
    description: "May cause slight changes in blood sugar levels",
    recommendation: "Monitor blood sugar levels if using moclobemide",
  },
  {
    name: "Linezolid",
    type: "medication",
    severity: "Low",
    description: "May cause slight changes in blood sugar levels",
    recommendation: "Monitor blood sugar levels if using linezolid",
  },
  {
    name: "Methylene Blue",
    type: "medication",
    severity: "Low",
    description: "May cause slight changes in blood sugar levels",
    recommendation: "Monitor blood sugar levels if using methylene blue",
  },
  {
    name: "Rasagiline",
    type: "medication",
    severity: "Low",
    description: "May cause slight changes in blood sugar levels",
    recommendation: "Monitor blood sugar levels if using rasagiline",
  },
  {
    name: "Safinamide",
    type: "medication",
    severity: "Low",
    description: "May cause slight changes in blood sugar levels",
    recommendation: "Monitor blood sugar levels if using safinamide",
  },
  {
    name: "Phenelzine",
    type: "medication",
    severity: "Low",
    description: "May cause slight changes in blood sugar levels",
    recommendation: "Monitor blood sugar levels if using phenelzine",
  },
];